"""Auto-generated by followUp/scripts/generate-citrix-asr-contracts.js.
Do not edit manually.
"""

ERROR_CODES = ["UNREACHABLE", "TIMEOUT", "INVALID_RESPONSE", "SESSION_MISMATCH", "SESSION_IN_USE", "NOT_DICTATING", "ALREADY_DICTATING", "PROCESSING", "PROGRAM_INACTIVE", "START_FAILED", "BAD_REQUEST", "HTTP_ERROR", "UNKNOWN"]
AUDIO_STATES = ["dictation", "processing", "activation", "inactive"]
RESULT_STATES = ["dictation", "processing", "complete", "not_found"]


def is_valid_error_code(value: str) -> bool:
    return isinstance(value, str) and value in ERROR_CODES


def is_valid_audio_state(value: str) -> bool:
    return isinstance(value, str) and value in AUDIO_STATES


def is_valid_result_state(value: str) -> bool:
    return isinstance(value, str) and value in RESULT_STATES
